//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVisitNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blacklist
    {
        public int blacklistID { get; set; }
        public int VisitorID { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string StaffID { get; set; }
    }
}
