//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVisitNG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BuildingCheck
    {
        public int AppID { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CreatedAt { get; set; }

        [Key]
        public int CheckID { get; set; }

        public Nullable<DateTime> CheckOutTime { get; set; }
        public string Status { get; set; }
    }
}
