//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVisitNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLoorCheck
    {
        public int FloorCheckID { get; set; }
        public int AppID { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> Floor { get; set; }
    }
}
