//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVisitNG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Security
    {
        [Key]
        public int SecID { get; set; }

        public string StaffID { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
