//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVisitNG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VisitorItem
    {
        [Key]
        public int itemID { get; set; }

        public int VisitorID { get; set; }
        public int AppID { get; set; }
        public string ItemName { get; set; }
        public string SerialNumber { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
